Задание 2
ozoncp/ocp-remind-api pull request #3
Opened 2021-07-20 19:59 UTC by mmatros

В пакете internal/utils реализованы экспортируемые функции BatchSlice, MirrorMap, FilterSlice и тесты для них.

2021-07-21 20:09 UTC, zerospiel requested changes

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +package utils
Очень часто тесты удобнее писать с использованием пакета github.com/stretchr/testify

Там просто сильно всё упрощается

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +		sourceMap := make(map[string]int)
Почти во всех тестах вполне подходит написание табличных тестов https://github.com/golang/go/wiki/TableDrivenTests

Это увеличиват читабельность и упрощает написание тестов в целом.

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +func TestCutSlice(t *testing.T) {
Имя тестов принято называть `TestFuncName`, тут скорее всего просто забыл поменять 😉

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +func TestMin(t *testing.T) {
Ещё по неймингу: неэкспортные (приватные) функции/методы принято называть так `Test_unexportedFunc`, какой-то официальной конвенции нет, так принято в сообществе 😊

Ну и в целом этот тест пропадёт из-за упрощения функции батчинга

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +		slice := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
здесь тоже табличный вполне нормально заходит, учитывая использование тестифая — будет шикарно

2021-07-21 20:09 UTC, zerospiel commented on internal/utils/utils_test.go
> +	{
чуть не понимаю смысла использования регионов, в го это очень редко используемая возможность, обычно используемая для привлечения внимания к какому-то критичному куску кода. В целом, аналогичного поведения можно достичь хорошим комментарием. 

В данном случае (и повыше в других тестах) это можно просто убрать 😉

2021-07-22 06:28 UTC, mmatros commented on internal/utils/utils_test.go
> +	{
Я пользовался этой возможностью для удобства создания тестов. Правда при этом происходит дублирование кода, но не значительное:)

2021-07-22 06:29 UTC, mmatros commented on internal/utils/utils.go
> +	chunksCount := getChunksCount(len(slice), chunkSize)
С одной функцией получилось даже красивее.

2021-07-22 06:35 UTC, mmatros commented on internal/utils/utils.go
> +	if sourceMap == nil {
Если я не ошибаюсь, то нулевая мапа будет паниковать при проверке длины?

2021-07-22 06:36 UTC, mmatros commented on internal/utils/utils.go
> +}
Убрал, сразу стало заметно меньше кода

2021-07-22 10:12 UTC, zerospiel commented on internal/utils/utils.go
> +	if sourceMap == nil {
Хороший тест-кейс для теста 😉 
```go
"github.com/stretchr/testify/require".NotPanics(t, func(){/*your func*/})
```

2021-07-22 19:46 UTC, mmatros commented on internal/utils/utils.go
> +	if sourceMap == nil {
неожиданно :)

2021-07-23 03:12 UTC, mmatros commented on internal/utils/utils_test.go
> +func TestMin(t *testing.T) {
Надо min было назвать unexportedMin(), или только тест Test_unexportedMin()?

2021-07-23 17:04 UTC, zerospiel requested changes

2021-07-23 17:04 UTC, zerospiel commented on internal/utils/utils_test.go
> +}
А здесь что-то типа такого, опять же, это не обязательно повторять, лишь предложение 😊

```go
func TestFilter(t *testing.T) {
	var testCases = []struct {
		name     string
		input    []int
		expected []int
	}{
		{
			name:     "some input, expect only non-filtered values",
			input:    []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20},
			expected: []int{1, 2, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20},
		},
		{
			name:     "empty, expect empty",
			input:    []int{},
			expected: []int{},
		},
		{
			name:     "nothing to filter, expect input",
			input:    []int{100, 200, 300},
			expected: []int{100, 200, 300},
		},
	}
	for _, tcase := range testCases {
		t.Run(tcase.name, func(t *testing.T) {
			assert.ElementsMatch(t, tcase.expected, Filter(tcase.input))
		})
	}
}
```

2021-07-24 07:45 UTC, zerospiel approved these changes

2021-07-24 07:45 UTC, merged