Feature/task 3
ozoncp/ocp-remind-api pull request #4
Opened 2021-07-26 20:02 UTC by mmatros

Добавил результат работы по третьему заданию

2021-07-27 00:24 UTC, zerospiel requested changes

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/remind_utils_test.go
> +	}
Упростим? Время, думаю, явно некритично 😅

```go
	now := time.Now()
	var tests = []struct {
		name      string
		input     []models.Remind
		batchSize int
		expected  [][]models.Remind
	}{
		{
			name: "simple batch",
			input: []models.Remind{
				models.NewRemind(1, 4, now, "first"),
				models.NewRemind(2, 5, now, "second"),
				models.NewRemind(3, 6, now, "third"),
			},
			batchSize: 2,
			expected: [][]models.Remind{
				{
					models.NewRemind(1, 4, now, "first"),
					models.NewRemind(2, 5, now, "second"),
				}, {
					models.NewRemind(3, 6, now, "third"),
				}},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			assert.Equal(t, test.expected, BatchReminds(test.input, test.batchSize))
		})
	}
```

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration_test.go
> +		errIsNil bool
`errIsNil` -> `expectErr`

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration_test.go
> +	err := ioutil.WriteFile(testFilename, []byte(""), 0755)
Лучше всегда использовать 0600 мод, просто для пущей безопасности, а любые другие моды — уже по необходимости. Иногда даже следует запрещать запись «владельцу» (как, например, с файлами go modules), но это тоже неуниверсальный кейс.

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration.go
> +		}()
Если я корректно понял из задания, то подобный `defer` должен быть всё же в теле цикла, а не лямбды

И, наверное, что-то другое предполагалось вместо закомментированных кусков 🙂

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration.go
> +			//fmt.Printf("file %v not opened\n", path)
Тут тоже вопрос про комментарии — возможно, что предполагалось логирование или может быть просто забыл убрать 🙂

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration.go
> +package utils
Емнип, по заданию, эти функции предполагалось реализовать в `cmd/<project>/main.go`, так что наверное имеет смысл потом перенести

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration_test.go
> +	}()
Можно упростить, ошибки не так критичны в данном случае (их и не будет, если только FS не заблокировать или вот не подать несуществующий файл)

```go
t.Cleanup(func() { _ = os.Remove(testFilename) }) // поставить после константы
```

2021-07-27 00:24 UTC, zerospiel commented on internal/utils/configuration_test.go
> +		fmt.Printf("Unable to write file: %v", err)
Я бы тут фаталился типа `t.Fatal`, а то странно дальше продолжать действо, если вдруг тестируемый файл не создался

2021-07-27 15:30 UTC, mmatros commented on internal/utils/utils.go
> +
 Добавил себе в  GoLand gofmt, go import и  gaoling-lint. Надо будет ещё хук добавить в гит.

2021-07-27 15:42 UTC, mmatros commented on internal/models/remind.go
> +type timestamp time.Time
Абсолютно согласен, делал этот тип только в соответствии с условием

2021-07-27 18:06 UTC, mmatros commented on internal/utils/configuration.go
> +			//fmt.Printf("file %v not opened\n", path)
Я изначально не до конца понял смысл задания. Но теперь понял :) Смысл в том, чтобы засунуть анонимную функцию в цикл - в этом случае после каждой итерации цикла будет выход из этой функции и срабатывание defer.

2021-07-27 20:11 UTC, mmatros commented on internal/models/remind.go
> +}
Я думал в общем случае, лучше всегда по ссылке передавать структуры . Чтобы не тратить время на копирование. Но надо более внимательно подойти к этому вопросу.

2021-07-28 17:06 UTC, zerospiel requested changes

2021-07-28 17:06 UTC, zerospiel commented on cmd/ocp-remind-api/main.go
> +	for i := 0; i < 100; i++ {
Короче, я точно не знаю что конкретно имелось ввиду по заданию, но скорее всего хотелось достичь эффекта получения знаний о том, о чём я писал:

```go
func main() {
	for i := 0; i < 10; i++ {
		i := i
		defer func() { println("real_i", i) }()
	}
	for i := 0; i < 10; i++ {
		defer func() { println("ten?", i) }()
	}
}
```

И второе: лямбду/функтор/анонимную функцию всё же лучше 1 раз инициализировать в начале функции, чем 100 раз её одинаковую объявлять заново. И, возможно, получится достичь эффекта. Давай попробуем так как-то сделать

2021-07-28 17:10 UTC, zerospiel commented on internal/models/remind.go
> +}
В общем случае — да, ты прав. Я тут просто напомнил о такой возможности :)

2021-07-28 21:26 UTC, zerospiel approved these changes

2021-07-28 21:26 UTC, merged