Добавлены интерфейсы Repo и Flusher. Добавлена генерация
ozoncp/ocp-remind-api pull request #5
Opened 2021-08-01 19:07 UTC by mmatros

моков через mockgen, имплементация flusher для Flusher. Добавлены
тесты с использованием ginkgo и gomega.

2021-08-02 12:50 UTC, mmatros commented
В тестах, в файле flusher_test.go имя тестируемой переменной тестируемой системы лучше так и указать - sut. Забыл это сделать.

2021-08-02 18:15 UTC, zerospiel requested changes

2021-08-02 18:15 UTC, zerospiel commented on internal/flusher/flusher_suite_test.go
> +	. "github.com/onsi/gomega"
Это очень плохая практика, особенно, учитывая, что используются только экспортные функции и структуры. Подобное можно делать в каких-то исключительных случаях и только для прямого доступа к unexported сущностям. Здесь и далее это не исключительный случай

Либо я не нашёл достоверные примеры использования фреймворка

2021-08-02 18:15 UTC, zerospiel commented on internal/repo/repo.go
> +package repo
Тут наверное аналогичное замечание имя пакета и структурок/интерфейсов. Может есть смысл типа на `entity` (тоже общее и ни о чём, но не могу лучше придумать) или `dao` может быть

2021-08-04 07:47 UTC, zerospiel approved these changes

2021-08-04 07:47 UTC, merged